### ISSUE TITLE
Icons and Today link disappear

### ISSUE THREAD

**Issue by hbkfabio** [StuartMacKay/django-daterange-filterspec#1]
maybe this is a Bug, or a user problem, but...
If you need remove the delete_selected actions from django-admin apps you need wrote this code...

```
def get_actions(self, request):
    actions = super(ArticulosAdmin, self).get_actions(request)
    if 'delete_selected' in actions:
        del actions['delete_selected']
        return actions

def has_delete_permission(self, request, obj=None):
    return False
```

look at http://pastebin.com/FXepv7BS and try.

If add this code in admin.py the Icon and today link disappear.
Why I dont know?

**Comment by StuartMacKay** [comment]
This is so old the problem must have gone away by now - closing.
